# Generated by Django 3.1.2 on 2022-02-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0003_auto_20220205_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
    ]
