# Generated by Django 3.1.2 on 2022-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0005_auto_20220209_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='outfits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worn_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_seen', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Wind', 'Wind'), ('Water', 'Water'), ('Earth', 'Earth'), ('Lightning', 'Lightning'), ('Random', 'Random')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='eye_colour',
            field=models.CharField(blank=True, choices=[('black', 'black'), ('brown', 'brown'), ('blue', 'blue'), ('grey', 'grey'), ('green', 'green')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, choices=[('black', 'black'), ('brown', 'brown'), ('blond', 'blond'), ('red', 'red'), ('grey', 'grey')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hair_length',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, choices=[('short', 'short'), ('medium', 'medium'), ('tall', 'tall')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='main_side',
            field=models.CharField(blank=True, choices=[('main', 'main'), ('side', 'side')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
