# Generated by Django 3.1.2 on 2022-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0006_auto_20220211_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField()),
                ('event', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
