# Generated by Django 3.1.2 on 2022-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0007_auto_20220212_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outfits',
            new_name='Outfit',
        ),
    ]
