# Generated by Django 3.1.2 on 2022-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0010_auto_20220213_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='outfit',
        ),
        migrations.AlterField(
            model_name='move',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
