# Generated by Django 3.1.2 on 2022-02-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0012_auto_20220215_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_name', to='light_novel.character'),
        ),
    ]
