# Generated by Django 3.1.2 on 2022-02-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0014_auto_20220215_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='comedy_trait',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='crushed_with_disappointment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='current_post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='despised_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='finance_as_child',
            field=models.CharField(blank=True, choices=[('Rich', 'Rich'), ('Middle', 'Middle'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='peaceful_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='raised',
            field=models.CharField(blank=True, choices=[('Nurtured', 'Nurtured'), ('Neglected', 'Neglected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('With Someone', 'With Someone')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_saved_by', to='light_novel.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_or_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='first_seen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
