# Generated by Django 3.1.2 on 2022-02-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0015_auto_20220215_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['date_time']},
        ),
    ]
