# Generated by Django 3.1.2 on 2022-02-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0016_auto_20220218_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name', 'element']},
        ),
    ]
