# Generated by Django 3.1.2 on 2022-02-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0017_auto_20220223_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
    ]
