# Generated by Django 3.1.2 on 2022-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0018_auto_20220223_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['date_field']},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='date_time',
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='event',
            field=models.TextField(blank=True, null=True),
        ),
    ]
