# Generated by Django 3.1.2 on 2022-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_novel', '0020_auto_20220227_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='superiority_complex',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
